/*
                         RADaFlow (forked from proteus)
    Proteus -- High-performance query processing on heterogeneous hardware.

                        Copyright (c) 2025
        Data Intensive Applications and Systems Laboratory (DIAS)
                École Polytechnique Fédérale de Lausanne

                            All Rights Reserved.

    Permission to use, copy, modify and distribute this software and
    its documentation is hereby granted, provided that both the
    copyright notice and this permission notice appear in all copies of
    the software, derivative works or modified versions, and any
    portions thereof, and that both notices appear in supporting
    documentation.

    This code is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. THE AUTHORS
    DISCLAIM ANY LIABILITY OF ANY KIND FOR ANY DAMAGES WHATSOEVER
    RESULTING FROM THE USE OF THIS SOFTWARE.
*/
#ifndef BLOCK_TO_TUPLES_HPP_
#define BLOCK_TO_TUPLES_HPP_

#include <platform/common/gpu/gpu-common.hpp>

#include "olap/util/parallel-context.hpp"
#include "operators.hpp"

/**
 * @brief Converts a packed block of data into a stream of individual tuples.
 *
 * This operator transitions  from block-wise processing (receiving a single
 * block from its child) to tuple-wise processing (producing individual tuples
 * to its parent). It is typically used after operators that produce packed
 * blocks, such as Scan or Pack, before operators that require tuple-at-a-time
 * input.
 *
 * During the code generation phase:
 * - The `produce_` method is called top-down and sets up state variables for
 *   buffering block pointers.
 * - The `consume` method is called bottom-up and generates the loop structure
 *   to iterate over the elements within the input block and call the parent's
 *   `consume` method for each tuple.
 *
 * During the execution phase:
 * - The generated code (from the `consume` method) processes the actual data.
 * - It iterates through the received block and 'unpacks' each tuple,
 *   passing it up the pipeline by effectively calling the code generated by the
 *   parent's `consume`.
 *
 * This operator supports both CPU and GPU execution and different granularities
 * for processing within the block.
 */
class BlockToTuples : public experimental::UnaryOperator {
 public:
  /**
   * @brief Constructs a BlockToTuples operator.
   *
   * @param child The child operator producing packed blocks.
   * @param wantedFields The list of expressions representing the fields to
   * unpack. At least one of these must be a BlockType.
   * @param gpu Whether this operator is intended for GPU execution.
   * @param granularity The processing granularity within the block (e.g.,
   * THREAD, GRID).
   */
  BlockToTuples(std::shared_ptr<Operator> const child,
                std::vector<expression_t> wantedFields, bool gpu = true,
                gran_t granularity = gran_t::GRID)
      : UnaryOperator(child),
        wantedFields(std::move(wantedFields)),
        granularity(granularity),
        gpu(gpu) {
    assert((gpu || granularity == gran_t::THREAD) &&
           "CPU can only have a THREAD-granularity block2tuples");
    assert(granularity != gran_t::BLOCK &&
           "BLOCK granurality is not supported yet");  // TODO: support BLOCK
                                                       // granularity
  }

  void produce_(OlapParallelContext *context) override;
  /**
   * @brief Generates code to consume a packed block and produce individual
   * tuples.
   *
   * This method is called during the bottom-up code generation phase. It
   * generates the loop that iterates through the input block and calls the
   * parent operator's `consume` method for each tuple. It also handles the
   * logic for releasing previously processed block buffers.
   *
   * @param context The parallel compilation context.
   * @param childState The state containing information about the input block
   * from the child operator.
   */
  void consume(OlapParallelContext *context,
               const OperatorState &childState) override;
  [[nodiscard]] bool isFiltering() const override { return false; }

  [[nodiscard]] RecordType getRowType() const override {
    // The output type is the unpacked version of the input block's type.
    // BlockTypes in the input are replaced by their nested types.
    std::vector<RecordAttribute *> attrs;
    for (const auto &attr : wantedFields) {
      auto a = attr.getRegisteredAs();
      auto type = a.getOriginalType();
      if (dynamic_cast<const BlockType *>(type)) {
        type = &(dynamic_cast<const BlockType *>(type)->getNestedType());
      }
      auto rec =
          new RecordAttribute(a.getRelationName(), a.getAttrName(), type);
      attrs.emplace_back(rec);
    }
    return attrs;
  }

  [[nodiscard]] bool isPacked() const override {
    assert(getChild()->isPacked());
    return false;
  }

 private:
  ProteusBareValue step(OlapParallelContext *context, llvm::IntegerType *type);
  void nextEntry(llvm::Value *mem_itemCtr, OlapParallelContext *context);
  virtual void open(Pipeline *pip);
  virtual void close(Pipeline *pip);

  const std::vector<expression_t> wantedFields;
  std::vector<StateVar> old_buffs;
  gran_t granularity;

  bool gpu;
};

#endif /* BLOCK_TO_TUPLES_HPP_ */
