/*
                         RADaFlow (forked from proteus)
    Proteus -- High-performance query processing on heterogeneous hardware.

                        Copyright (c) 2025
        Data Intensive Applications and Systems Laboratory (DIAS)
                École Polytechnique Fédérale de Lausanne

                            All Rights Reserved.

    Permission to use, copy, modify and distribute this software and
    its documentation is hereby granted, provided that both the
    copyright notice and this permission notice appear in all copies of
    the software, derivative works or modified versions, and any
    portions thereof, and that both notices appear in supporting
    documentation.

    This code is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. THE AUTHORS
    DISCLAIM ANY LIABILITY OF ANY KIND FOR ANY DAMAGES WHATSOEVER
    RESULTING FROM THE USE OF THIS SOFTWARE.
*/
#ifndef CPU_TO_GPU_HPP_
#define CPU_TO_GPU_HPP_

#include "device-cross.hpp"
#include "olap/util/parallel-context.hpp"
#include "operators.hpp"
/**
 * @brief Operator that transfers execution and data synchronously from the CPU
 * to the GPU.
 *
 * The `CpuToGpu` operator is a concrete implementation of a `DeviceCross`
 * operator specialized for transitioning data and control flow from a CPU
 * pipeline to a GPU pipeline. It acts as a compiled pipeline breaker. This
 * operator handles the process of generating the necessary GPU kernel code for
 * the downstream operations and orchestrating its synchronous execution from
 * the CPU side during runtime. This includes preparing data for transfer to the
 * GPU (passed as kernel parameters) and managing the CUDA stream for the kernel
 * launch.
 *
 * During the compilation phase (`produce_` and `consume`):
 * - The `produce_` method is called top-down. It is responsible for initiating
 *   the code generation process for the *GPU side* of the pipeline segment that
 *   will execute after the transfer. It sets up the parallel context for GPU
 * code generation, calls `generateGpuSide` to produce the kernel code, and
 * captures the resulting compiled GPU pipeline (`gpu_pip`). It then restores
 * the context for CPU code generation, registers `open` and `close` callbacks
 * for the CPU pipeline segment, and sets up state variables to hold the kernel
 * pointer and stream handle before calling `produce` on its child.
 * - The `consume` method is called bottom-up by the child operator (which runs
 *   on the CPU). It generates the LLVM IR code responsible for taking the
 *   input data from the `childState`, preparing this data to be passed as
 *   parameters to the GPU kernel, and generating the call to launch the GPU
 *   kernel asynchronously on a CUDA stream. The synchronous nature implies
 *   that the CPU side must eventually wait for the GPU execution to complete,
 *   which is handled by the stream synchronization in the `close` callback.
 *
 * During the execution phase:
 * - When the compiled code generated by the `consume` method is executed on the
 *   CPU, it prepares the actual data and launches the pre-compiled GPU kernel
 *   (`gpu_pip`) with these parameters on a CUDA stream.
 * - The `open` callback for the CPU pipeline segment is executed before the
 *   consume loop starts, typically to create and store the CUDA stream and
 * kernel pointer.
 * - The `close` callback is executed after the CPU consume loop finishes.
 *   It is responsible for synchronizing the CUDA stream, ensuring the GPU
 *   computation has finished before the CPU pipeline fully completes its
 * execution segment, and cleaning up stream resources.
 *
 * This synchronous handoff materializes data out of CPU registers into memory
 * (which is then accessible or transferred to the GPU) and explicitly waits for
 * the GPU to finish, necessitating a significant pipeline break and
 * synchronization point.
 */
class CpuToGpu : public DeviceCross {
 public:
  /**
   * @brief Constructs a CpuToGpu operator.
   *
   * @param child The child operator producing data on the CPU.
   * @param wantedFields The list of RecordAttributes representing the data
   * fields that need to be transferred to the GPU kernel as parameters.
   */
  CpuToGpu(std::shared_ptr<Operator> const child,
           const std::vector<RecordAttribute *> &wantedFields)
      : DeviceCross(child), wantedFields(wantedFields) {}

  ~CpuToGpu() override { LOG(INFO) << "Collapsing CpuToGpu operator"; }

  void produce_(OlapParallelContext *context) override;
  void consume(OlapParallelContext *const context,
               const OperatorState &childState) override;
  /**
   * @brief Generates the LLVM IR code for the GPU kernel.
   *
   * This helper method is called by `produce_`. It configures the LLVM context
   * for GPU code generation, defines the parameters for the GPU kernel based
   * on `wantedFields`, and then calls `getParent()->consume` to generate the
   * actual processing logic that will execute *on the GPU*. The generated
   * function becomes the GPU kernel that will be launched from the CPU side
   * during execution.
   *
   * @param context The parallel compilation context set up specifically for GPU
   * code generation.
   */
  virtual void generateGpuSide(OlapParallelContext *context);

  RecordType getRowType() const override { return wantedFields; }

  DeviceType getDeviceType() const override {
    assert(getChild()->getDeviceType() == DeviceType::CPU);
    return DeviceType::GPU;
  }

 private:
  const std::vector<RecordAttribute *> wantedFields;
  /// Pointer to the generated and compiled GPU pipeline (kernel).
  /// Populated during `produce_`.
  PipelineGen *gpu_pip;
  /// State variable ID in the CPU pipeline to store the pointer to the
  /// generated GPU kernel function.
  StateVar childVar_id;
  /// State variable ID in the CPU pipeline to store the CUDA stream handle used
  /// for launching the kernel.
  StateVar strmVar_id;
};

#endif /* CPU_TO_GPU_HPP_ */
