import pandas as pd
from absl import logging


def peek_line(file, index=0):
    pos = file.tell()  # Remember the current position
    next_line = file.readline()
    for _ in range(0, index):
        next_line = file.readline()
    file.seek(pos)
    return next_line


def read_amd_pcm_out(file_path):
    """
    Read a log file generated by AMDuProfPcm with the `-s`/ time stamps in timeseries switch

    :param file_path: path to the file generated by AMDuProfPcm
    :returns: a data frame of the time series data
    """
    with open(file_path, 'r') as file:
        line = file.readline();
        while line and 'Profile Time:' not in line:
            line = file.readline();
            pass
        if not line:
            logging.fatal("Unexpected format for AMDuProfPcm file")

        # if there are aggregations, then these will be aggregations, headers and first row of data
        # else headers then first row of data, then second row of data
        maybe_aggregations = peek_line(file, 0).split(",")
        maybe_headers = peek_line(file, 1).split(",")
        maybe_data = peek_line(file, 1).split(",")

        aggregations = None
        headers = None

        # the AMDuProfPcm `-s` switch adds a Timestamp column which aggregations don't apply to
        if len(maybe_aggregations) + 1 == len(maybe_headers):
            logging.info(f"Found aggregations in {file_path}")
            aggregations = maybe_aggregations
            headers = maybe_headers
            print(f"len aggregations {len(aggregations)} len headers {len(headers)}")
            if len(headers) != len(maybe_data):
                logging.fatal("failed to parse data")
            # advance past the aggregations so file starts from headers so that pandas can read the csv
            file.readline()
        else:
            headers = maybe_aggregations
            # maybe_headers should be first row of data
            if len(headers) != len(maybe_headers):
                logging.fatal("failed to parse data")

        if 'Timestamp' not in headers:
            logging.fatal("No support for parsing AMDuProfPcm without Timestamps (`AMDuProfPcm -s`)")

        df = pd.read_csv(file, parse_dates=[0], date_format='%H:%M:%S:%f')
        # AMD PCM output is time from start of program.
        if 'Timestamp' in df.columns:
            df['Timestamp'] = df['Timestamp'] - pd.Timestamp('1900-01-01')

        if aggregations is not None:
            rename_map = {}
            first_rename_col = 1
            current_agg = ''
            for i in range(first_rename_col, len(df.columns)):
                if 'Package' in aggregations[i - 1] or 'CCD' in aggregations[i - 1] or 'CCX' in aggregations[
                    i - 1] or 'Core' in aggregations[i - 1]:
                    current_agg = aggregations[i - 1]
                # pandas adds .{number} for duplicated column names. Remove that now that we are renaming columns with the aggregations
                if len(df.columns[i].split('.')) > 1:
                    new_col_name = f"{current_agg} {''.join(df.columns[i].split('.')[:-1])}"
                else:
                    new_col_name = f"{current_agg} {df.columns[i]}"
                rename_map[df.columns[i]] = new_col_name
            df.rename(columns=rename_map, inplace=True)
    return df
